name: Neovim

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        version:
          - stable
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - uses: rhysd/action-setup-vim@v1
        id: nvim
        with:
          neovim: true
          version: "${{ matrix.version }}"
      - name: Run tests
        env:
          THEMIS_VIM: ${{ steps.nvim.outputs.executable }}
        run: |
          ./vim-themis/bin/themis
